################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-discovery-continuousc-ca
data:
  ca.crt: {{ .Values.app.ca-domain}}
