################################################################################
# Copyright ContinuousC. Licensed under the "Elastic License 2.0".             #
################################################################################

apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-discovery
